### ISSUE TITLE
Error log huge 15gb size, some issue with plugin display.php

### ISSUE THREAD

**Issue by ezzmay007** [flowdee/widget-options#91]
[27-Apr-2020 21:34:20 UTC] PHP Warning:  Use of undefined constant snack - assumed 'snack' (this will throw an Error in a future version of PHP) in /home/bonza/public_html/wp-content/plugins/widget-options/includes/widgets/display.php(360) : eval()'d code on line 1

[27-Apr-2020 21:34:20 UTC] PHP Warning:  A non-numeric value encountered in /home/bonza/public_html/wp-content/plugins/widget-options/includes/widgets/display.php(360) : eval()'d code on line 1

**Comment by flowdee** [comment]
Hey @ezzmay007  could you please forward the text/code what you are pasting in the 'Logic' text area ? 

Feel free to also share a screenshot of the related widget settings

**Comment by ezzmay007** [comment]
Hi thanks for taking the time to respond.

I only use logic on 4 widgets, the aim is to show only posts from certain categories in the sidebar. so when your on [this](https://www.subscriptionboxaustralia.com/category/gift-guides/) page, you see other buying guides, and on [this](https://www.subscriptionboxaustralia.com/category/subscription-box-reviews/) page, you see other review posts. it works as needed, but maybe the issue lies here somewhere. (screenshots provided).

![Snap 2020-04-29 at 07 43 06](https://user-images.githubusercontent.com/64442501/80542300-183c9000-89f0-11ea-8da9-2c77519fd055.png)
![Snap 2020-04-29 at 07 43 35](https://user-images.githubusercontent.com/64442501/80542341-25f21580-89f0-11ea-8ffd-e2961d82aa8e.png)
![Snap 2020-04-29 at 07 44 09](https://user-images.githubusercontent.com/64442501/80542346-27234280-89f0-11ea-8c54-d70388b8e9b7.png)
![Snap 2020-04-29 at 07 44 51](https://user-images.githubusercontent.com/64442501/80542348-27bbd900-89f0-11ea-930a-1347dd9cf078.png)

The only other time I use this plugin is for a sprite sheet, one sprite sheets shows on mobile and one on desktop, so I use the hide/show on devices for that. (screenshots provided)

![Snap 2020-04-29 at 08 01 48](https://user-images.githubusercontent.com/64442501/80542378-373b2200-89f0-11ea-9022-0edd5f173adb.png)
![Snap 2020-04-29 at 08 02 25](https://user-images.githubusercontent.com/64442501/80542379-386c4f00-89f0-11ea-9879-96f624e8deb6.png)

The funny part for me is the error above shows the word "snack" but nowhere do I use the single word snack, 
I use snacks-candy to define a post category
and I use snack-boxes, to define a sprite sheets id
both of which work fine onsite, but there is some unknown issue with this plugin that constantly blows up my error log

Hopefully your smart brain can figure this out, because I'm at a loss but i adore this plugin and don't want to lose it.

Thanks
Erin

**Comment by ezzmay007** [comment]
all good im pretty sure i fixed it, wasn't your fault at all, and my logic code issue. thanks heaps anyways

**Comment by flowdee** [comment]
Happy to hear!
